### ISSUE TITLE
Alire question

### ISSUE THREAD

**Issue by ethindp** [stcarrez/ada-util#20]
So, I know this isn't necessarily related to utilada but I'm really wanting to use Utilada.

I've pulled in the library (latest version 2.4.1) because the one on alire is majorly out of date. However, though I've got the utilada dependency, I need either utilada_curl or utilada_aws for the HTTP client. What is the (proper) way for doing this when I already have utilada from git? I included it like this:

```
alr with utilada --use https://github.com/stcarrez/ada-util --commit 02f8a8ddf4e19ed469c25f96acd0000b64f3eec8
```

**Comment by stcarrez** [comment]
Good question! I've never done it.

You can add the following:

```Ada
with "utilada_curl";
```
in your GNAT project after the `with "config/xxx.gpr";`.
It works for Curl because the GNAT project of Ada Util is located in a directory that is visible.

If you want to use `utilada_aws`, it could be a little bit more difficult. I guess you will need to run
`alr with aws` before.

With this trick, I was able to build a simple example:

```Ada
with Util.Http.Clients;
with Util.Http.Clients.Curl;
procedure Tst_Util is
begin
   Util.Http.Clients.Curl.Register;
end Tst_Util;
```

If you have problems with AWS such as a failure to build `utilada_aws`, it means the AWS version is not compatible with `utilada_aws`. I've made several fixes to solve this by supporting more AWS versions.
Then, you may have to try the following commit: efe630c97fad95a035f1d3ba9b35dcbb5c058aa4

Well, I've done the following:

```
alr init tst_util --bin
cd tst_util
alr with utilada --use https://github.com/stcarrez/ada-util --commit efe630c97fad95a035f1d3ba9b35dcbb5c058aa4
```

Then, edited the GNAT project `tst_util.gpr`:
```Ada
with "config/tst_util_config.gpr";
with "utilada_aws";
with "utilada_curl";
project Tst_Util is
...
end Tst_Util;
```

Then, I've used the following:

```Ada
with Util.Http.Clients;
with Util.Http.Clients.AWS;
procedure Tst_Util is
begin
   Util.Http.Clients.AWS.Register;
end Tst_Util;
```
and it worked.

**Comment by ethindp** [comment]
Thank you so much! I was thinking I'd have to use `alr with --from` or something like that. I really like utilada. Combined with simple_components, you've got a huge amount of power and flexibility at your fingertips.
