### ISSUE TITLE
Update utilada and related crates on alire to latest version

### ISSUE THREAD

**Issue by ethindp** [stcarrez/ada-util#21]
Currently the latest alire crate version for utilada and friends is version 2.1.0. Not sure if this is an LTS or whatnot, but since the later releases aren't actual branches, you can't checkout (say) version 2.4.1 with `alr with --branch` (git complains that 2.4.1 isn't a commit or branch). I can checkout master, but that's not stable.

**Comment by stcarrez** [comment]
Yes, in fact I don't create branch but I put a tag instead. I'm creating a branch when I have some bug fix to put specifically on a branch. When I do this, I can use the tag to create the branch afterwards.

There is no `--tag=TAG` option in Alire but it would make sense!

It's not easy to have a crate integrated and last time I've submitted a pull request it was stuck and it took months to be integrated. For another project it was smooth and fast.

Since then, I've not submitted any update for Ada Util due to the energy it requires for it to be integrated.

After FOSDEM 2022, I'll try to make a 2.5.0 release for Ada Util and have it integrated.

**Comment by ethindp** [comment]
That would be good. I can't use version 2.4.1 as a submodule for right now, which is quite sad because I *love* utilada. I mean, maybe there's a way to use the 2.4.1 tag as a branch?

**Comment by stcarrez** [comment]
I've created a branch `ada-util-2.4.1`. I tried with 2.4.1 but it failed probably because I already have the tag 2.4.1
Can you try with `--branch ada-util-2.4.1`?

**Comment by ethindp** [comment]
Yep, it worked.
