### ISSUE TITLE
Building ada-util without ./configure & make

### ISSUE THREAD

**Issue by mterron** [stcarrez/ada-util#9]
Is there a way to provide a simpler build experience for ada-util? I'd love to be able to just `gprbuild` it without having to install a whole MSYS2/mingw environment on windows and hope it works.

**Comment by ghost** [comment]
gprinstall could be an option too right?

**Comment by stcarrez** [comment]
Since the integration with Alire, you can build without running configure.
However, you may have to specify the `UTIL_ASM_TYPE` and the `UTIL_OS` type variables.

For a simple Linux 64-bit build, use:

```
gprbuild -aP.alire -Putilada_sys -p
```

For a Linux 32-bit build, use

```
gprbuild -aP.alire -Putilada_sys -p -XUTIL_OS=linux32
```
For Windows-64 try:

```
gprbuild -aP.alire -Putilada_sys -p -XUTIL_OS=win64
```

Checkout the file `.alire/utilada_conf.gpr` for other alternatives.

You can also use `gprinstall` for the installation:

```
gprinstall -aP.alire -Putilada_core -p
gprinstall -aP.alire -Putilada_base -p
gprinstall -aP.alire -Putilada_sys -p
gprinstall -aP.alire -Putilada_aws -p
gprinstall -aP.alire -Putilada_curl -p
gprinstall -aP.alire -Putilada_xml -p
```

I've never tried to build on Windows without msys2.
I don't know if it works. I suspect there will be problems.

**Comment by stcarrez** [comment]
I've added some explanation in the readme. Thanks for the suggestion.
